package rest

import (
	"github.com/labstack/echo/v4"
	_ "github.com/oeoen/policy/pkg/handler/rest/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/oeoen/policy/pkg/police"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func getRoutes(e *echo.Echo, m police.Manager, c police.Configuration) {
	if e == nil {
		e = echo.New()
	}

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.POST("/enforce/tenant/:tenant", Enforce(m, c))
	e.POST("/policies", CreatePolicy(m, c))
	e.GET("/policies/:policy_id", GetPolicy(m, c))
	e.PUT("/policies/:policy_id", UpdatePolicy(m, c))
	e.GET("/policies/tenant/:tenant", GetPolicyTenant(m, c))
	e.GET("/policies/resources", GetPolicyResources(m, c))
	e.GET("/policies/subjects", GetPolicySubjects(m, c))
	e.DELETE("/policies/:policy_id", DeletePolicy(m, c))
	e.GET("/policies", FetchPolicy(m, c))

	e.POST("/policies/tenant/:tenant/roles", UpsertPolicyRole(m, c))
	e.GET("/policies/tenant/:tenant/subjects/:subject/roles", GetSubjectRoles(m, c))
	e.GET("/policies/tenant/:tenant/roles/:policy/subjects", GetRoleSubjects(m, c))
	e.GET("/policies/tenant/:tenant/roles/:policy", GetPolicyRole(m, c))
	e.DELETE("/policies/tenant/:tenant/roles/:policy/subjects/:subject", DeleteSubjectsRole(m, c))

}
